version: 2

jobs:
  build:
    working_directory: ~/quartic-python
    
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - quartic-python-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
            - quartic-python-{{ .Branch }}
            - quartic-python-develop

      - run: |
          python3 -m venv .env
          . .env/bin/activate
          pip install -r requirements.txt

      - save_cache:
          key: quartic-python-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - .env

      - run: |
          . .env/bin/activate
          python -m pytest --junitxml=test-reports/pytest.xml

      - store_test_results:
          path: test-reports/
