version: 2

jobs:
  build:
    working_directory: ~/quartic-python
    
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - quartic-python-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
            - quartic-python-v2-{{ .Branch }}
            - quartic-python-v2-develop

      - run:
          name: Install requirements
          command: |
            python3 -m venv .env
            . .env/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            . .env/bin/activate
            python setup.py test --addopts=--junitxml=test-reports/pytest.xml

      - run:
          name: Run linter
          command: |
            . .env/bin/activate
            python setup.py lint

      - save_cache:
          key: quartic-python-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - .env

      - store_test_results:
          path: test-reports/
